# Generated by Django 4.1.7 on 2023-03-12 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('text_form', models.TextField(verbose_name='форма текста')),
                ('data_time', models.DateTimeField()),
                ('establishments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_establishmentss', to='project.establishments', verbose_name='Здания')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='FormHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('establishments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_history_establishmentss', to='project.establishments', verbose_name='Здания')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_history', to='form.form', verbose_name='Мои запросы')),
            ],
            options={
                'verbose_name': 'Мой запрос',
                'verbose_name_plural': 'Мои запросы',
            },
        ),
    ]
