# Generated by Django 4.1.7 on 2023-04-14 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='establishments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form', to='project.establishments', verbose_name='Здания'),
        ),
        migrations.AlterField(
            model_name='formhistory',
            name='establishments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_history_establishments', to='project.establishments', verbose_name='Здания'),
        ),
        migrations.AlterField(
            model_name='formhistory',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formhistories', to='form.form', verbose_name='Мои запросы'),
        ),
    ]
